<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>AlgoTrading.RuleEditor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AlgoTrading/AlgoTrading.Models/AlgoTrading.Models.csproj" />
  </ItemGroup>
</Project>

